### ISSUE TITLE
Add www.unionizeme.org to "Projects Using Purescript"

### ISSUE THREAD

**Issue by jasonzoladz** [purescript/purescript.github.io#101]
All of the dynamic pages (sign up, dashboard, etc.) are in Purescript (using `-react`, `-affjax`, `-routing`, et al.).  The static pages are `lucid`.

www.unionizeme.org

www.unionize.me

**Comment by paf31** [comment]
Looks good. Is the source available anywhere?

**Comment by jasonzoladz** [comment]
Not yet.  I'll need to extract the front end from the repo that includes the (closed-source) backend, and think hard about whether open-sourcing the front end will expose us to security risk.  (However, my initial reaction is that it's possible.)

**Comment by kRITZCREEK** [comment]
These websites don't seem to exist anymore, so I'll close this.
