### ISSUE TITLE
Move content over to docs repo

### ISSUE THREAD

**Issue by paf31** [purescript/purescript.github.io#102]
cc @hdgarrood @garyb 

The website changes slowly, but I think we could update the docs repo at a much higher rate, mostly because we don't have to rerun the generator every time we want to test out a change.

So an alternative is to push more content into the docs repo. I quite like this idea, and we could even take it so far as to reduce purescript.org down to one well-organized page of links to external resources.

Any thoughts?

**Comment by hdgarrood** [comment]
Sounds good to me &mdash; although I think I would quite like to have some kind of generator process on the docs repo eventually.
