### ISSUE TITLE
Community section on homepage

### ISSUE THREAD

**Issue by aforemny** [purescript/purescript.github.io#125]
Hi,

I am currently evaluating using PureScript for a project I have in mind and I would like to talk to people getting their advice. I feel like the homepage purescript.org is missing a community section that tells me where to get in touch with people from the community. Is there a Slack, IRC or mailing list? Or maybe I am just blind? :)

**Comment by soupi** [comment]
There's a fairly active community for purescript but you are right that this is not really stated anywhere and it probably should be.

- [Slack](https://functionalprogramming.slack.com/) - #purescript channel on the functional programming server is the most active gathering of purescript programmers
- IRC: irc://irc.freenode.net/purescript - #purescript on freenode exists but it seems like everyone moved to Slack
- [Mailing list](https://groups.google.com/forum/#!forum/purescript)
- [Online Gatherings](https://github.com/purescript/documentation/blob/master/ecosystem/PureScript-Meetups.md) - Held twice a month.

**Comment by aforemny** [comment]
@soupi Thanks a bunch!

**Comment by freddie-freeloader** [comment]
I found those links through web search and then this issue. So thanks Gil! :sun_with_face: 

Are there opinions on whether this should be placed on the landing page?
In my opinion this could be really helpful for beginners and might be worth the effort. :slightly_smiling_face:

**Comment by chexxor** [comment]
If someone adds a Community section, it would be a nice place to link to [discourse.purescript.org](https://discourse.purescript.org).

**Comment by aforemny** [comment]
@chexxor Thank you very much. I think it turned out great!
