### ISSUE TITLE
Fix purescript.org domain settings for valid HTTPS certificate 

### ISSUE THREAD

**Issue by hrantzsch** [purescript/purescript.github.io#130]
![image](https://user-images.githubusercontent.com/6616713/44000295-89c03f26-9e1d-11e8-8394-db10b4090c87.png)

The certificate issued by Github (for *.github.io) is not valid for purescript.org. Since recently, Github supports HTTPS for custom domains: https://blog.github.com/2018-05-01-github-pages-custom-domains-https/
It seems some additional configuration for the domain is needed, but judging from the instructions, it should be a simple fix.

**Comment by sgalal** [comment]
Is there any plan to solve that?

**Comment by mbbx6spp** [comment]
I would love to help and get this sorted too but don't have access.

**Comment by hdgarrood** [comment]
Phil has just transferred the DNS over to me and I've updated the DNS configuration, which seems to have fixed this. Please let me know if I've missed anything.
