### ISSUE TITLE
Add link to my learning repo

### ISSUE THREAD

**Issue by JordanMartinez** [purescript/purescript.github.io#132]
I propose adding a link to my learning repo [here](https://github.com/JordanMartinez/purescript-jordans-reference) since it (currently) has more up-to-date documentation than a number of other materials.

**Comment by JordanMartinez** [comment]
Any comments on this?

**Comment by kRITZCREEK** [comment]
I think https://github.com/purescript/documentation is the better place for that link, that way we have a single place to collaborate/coordinate on keeping our resources up-to-date.

**Comment by JordanMartinez** [comment]
I've opened an issue there.
