### ISSUE TITLE
Mention Spago as a recommended build tool

### ISSUE THREAD

**Issue by LiamGoodacre** [purescript/purescript.github.io#137]
Currently the website mentions:

> The recommended build tool for beginners is Pulp, which can be installed using `npm`:
> ```npm install -g pulp bower```

I think it'd be useful to first mention `spago`, then `pulp` & `bower` as an alternative.

Thoughts?

**Comment by hdgarrood** [comment]
I agree, but I think we should make sure the documentation repo agrees - if I remember correctly there’s a getting started guide in there which ideally would be updated at the same time

**Comment by hdgarrood** [comment]
This was resolved by #138
