### ISSUE TITLE
purescript.org needs a Packages section

### ISSUE THREAD

**Issue by alexchandel** [purescript/purescript.github.io#17]
Purescript packages are scattered and hidden. It takes some digging for a noob just to *realize* that purescript packages are on Bower—never mind installing or building them. And even if they are on [bower](http://bower.io/search/?q=purescript), there isn't a good front-end for browsing them. Compare to [Elm's Package Catalog](http://package.elm-lang.org/), which is linked directly from Elm's homepage and provides all the information necessary to discover and install packages.

Given that much of Purescript is in libraries (tuples, arrays, dom, etc), this is even more important for Purescript!

Even if it just had an [All Packages](http://bower.io/search/?q=purescript) link and the following noob-bootstrapping sections, it would be a huge improvement! (edited:)

## Get Started
Purescript projects use [Node.js](http://nodejs.org/) infrastructure rather than any language-specific solution. In particular, packages are installed with [Bower](http://bower.io/), and projects are built using a build system like [Grunt](http://gruntjs.com/getting-started) or [Gulp](https://github.com/gulpjs/gulp/blob/master/docs/getting-started.md). All of these can be installed through Node's package manager, [npm](https://www.npmjs.com/).

## Install Packages
Use Bower to install packages to your project directory:
```sh
bower install purescript-package-name
```

Bower is sandboxed, so all packages are installed on a per-project basis. Bower can also record your project's dependencies with `--save`. The full list of bower commands is [available here](http://bower.io/docs/api/).

## Build Project
Use a build system like Gulp or Grunt to build your project.

### Gulp
Install `gulp` and `gulp-purescript` and initialize your project:
```sh
npm install gulp gulp-purescript
npm init
# answer prompt
```

Create a Gulpfile in your project and add a purescript task:
```js
// gulpfile.js
var gulp = require('gulp');
var purescript = require('gulp-purescript');
var DEV = true;

gulp.task('purescript', function(){
	gulp.src(['src/**/*.purs', 'bower_components/*/src/**/*.purs']).pipe(purescript.psc({
		noOpts: DEV,
		runtimeTypeChecks: false,
		noMagicDo: false,
		verboseErrors: true,
		main: true,
		modules: ['Main']
	})).pipe(gulp.dest('output/'));
});

gulp.task('default', ['purescript'], function(){});
```

Run it with `gulp`.

### Grunt
Install `grunt`, `grunt-purescript`, and others and initialize your project:
```sh
npm install grunt grunt-purescript grunt-contrib-copy grunt-contrib-clean grunt-execute
npm init
# answer prompt
```
Create a Gruntfile in your project and add a purescript task. [One is available here](https://github.com/purescript-contrib/grunt-init-purescript/blob/master/root/Gruntfile.js).

Run it with `grunt`.

**Comment by paf31** [comment]
I agree that visibility is not ideal right now, but have you seen [Pursuit](http://pursuit.purescript.org)? The plan is to turn it into the online package database.

**Comment by alexchandel** [comment]
I was looking for that earlier! That's part of what I had in mind, but a couple paragraphs on the homesite to point newcomers (particularly those who have never heard of Bower, Grunt, Haskell, or even Node before) in the right direction can strongly influence first impressions.

**Comment by garyb** [comment]
I think it would be nice to have an actual article on the libraries, perhaps taking something like the "recommended libraries" section from the wiki and turning it into a page on the site.

**Comment by alexchandel** [comment]
Actually, it seems [pulp](https://github.com/bodil/pulp) is the way to go for newcomer recommendations. There's no reason it shouldn't be mentioned on purescript.org. In fact, it's a little insane I've made it this far without running across it.

**Comment by paf31** [comment]
Superceded by #14 and #42. Closing this..
