### ISSUE TITLE
favicon?

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript.github.io#21]
I could probably have a go at making one out of the logo.

**Comment by paf31** [comment]
:+1:

**Comment by garyb** [comment]
I think @goodworkson made one already actually and I was too lazy/forgetful to actually put it on here. I'll have a look.

**Comment by paf31** [comment]
@garyb Were you able to find the favicon file?

**Comment by garyb** [comment]
No I wasn't in the end. I did look at doing something about this though and I guess I forgot to report back. Basically: the logo looks like a horrendous mess at favicon size, you can't even tell what it is. I spent quite a while trying to tweak it at pixel resolution but couldn't get something that looked right, I'll take another look at it though, I'm sure there's some kind of trickery that might make it workable.
