### ISSUE TITLE
Tidy up download page

### ISSUE THREAD

**Issue by paf31** [purescript/purescript.github.io#33]
Are all of the options on the download page still up to date? In particular, Brew, Chocolatey and AUR? Should we cut down the recommendations to just NPM and Hackage to keep things simple?

**Comment by garyb** [comment]
I'd be in favour of that, purely because those are the only ones we maintain ourselves. I think some of the other ones do get updated too, but I'm not sure how frequently.

I guess add Stack/Stackage too.
