### ISSUE TITLE
foreign-generic article

### ISSUE THREAD

**Issue by paf31** [purescript/purescript.github.io#46]
If this looks okay, I'll put together a PR to add it as an article:

https://gist.github.com/paf31/1fe162e9d5254264823b

**Comment by garyb** [comment]
Looks great! Maybe we should mention that relying on `gEq` and the like has a performance tradeoff though.

**Comment by paf31** [comment]
Yes, good point, I'll add that.

**Comment by paf31** [comment]
How's [this](https://gist.github.com/paf31/1fe162e9d5254264823b#performance-concerns)?

@gbaz I hope you don't mind me putting your name and link into the article?

**Comment by garyb** [comment]
Perfect :+1:

**Comment by gbaz** [comment]
no prob giving me credit :-)

article looks good too.

**Comment by paf31** [comment]
Thank you both, I'll put a PR together then.
