### ISSUE TITLE
Code blocks are badly formatted in articles

### ISSUE THREAD

**Issue by paf31** [purescript/purescript.github.io#84]
I noticed this in the FFI article.

**Comment by garyb** [comment]
Hmm yeah. Looks like it's those that are highlighted; they're wrapped in a `div` before the `pre` that means the CSS rule isn't being applied. Looks like the `main section > pre` rule needs applying to `main section > div.sourceCode > pre` too.

We could possibly take out the `>` instead, but it might cause problems elsewhere.
