### ISSUE TITLE
Partial article

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript.github.io#91]
I just wrote https://github.com/purescript/purescript/wiki/The-Partial-type-class and put it on the wiki, but perhaps it the website would be a better place to put it? What do you think?

**Comment by garyb** [comment]
Article is great, and yeah I think it would go well on the site :+1:. Nice example with the `Partial` propagation too!

A few minor things though:

- Very minor nitpick, but you don't have to export as `V3()`, just `V3` will do the trick
- References like `Partial.Unsafe.unsafePartial` and `Partial.crash` won't work in 0.9, unless there's an `import Partial.Unsafe as Partial.Unsafe`, etc. so perhaps we'd better avoid them in the examples?

**Comment by hdgarrood** [comment]
Thanks :) Agreed re both of those. I'll address them and send a PR.
